name: sdm_mini_project
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.3
  flutter_spinkit: "^4.1.2"
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  # cloud_firestore: ^1.0.5
  carousel_slider: ^3.0.0
  dots_indicator: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - lib/Config/i18n/en.json
  #   - lib/Config/i18n/th.json
  fonts:
    - family: Kanit
      fonts:
        - asset: fonts/Kanit/Kanit-Regular.ttf
        - asset: fonts/Kanit/Kanit-Italic.ttf
          style: italic
    - family: Sarabun
      fonts:
        - asset: fonts/Sarabun/Sarabun-Regular.ttf
